# This is a taskfile for the Task tool. See https://taskfile.dev for install instructions.

version: '3'

env:
  OWNER: I'm WGO

tasks:
  test:
    desc: For all temporay test function
    cmds:
      - echo "test"
  
  text-blue:
    desc: run ./function.sh with blue color
    cmds:
      - COLOR=blue ./run-function.sh